[[redirects]]
from = "/panel"
to = "/index.html"
status = 200

[[redirects]]
from = "/profile"
to = "/index.html"
status = 200

[[redirects]]
from = "/send-message/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 404
